version: '3.7'
services:
  helloworld:
    env_file:
      - .env
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - target: ${EXPOSE_PORT}
        published: ${SERVER_PORT}
        protocol: tcp
        mode: host