schema: ./src/schema/schema.graphql
extensions:
  codegen:
    generates:
      ./src/generated-types.ts:
        config:
          scalars:
            GraphbackDate: Date
            GraphbackDateTime: Date
            GraphbackJSON: any
            GraphbackJSONObject: '{ [key: string]: any }'
            GraphbackObjectID: string
            GraphbackTime: string
            GraphbackTimestamp: number
        plugins:
          - add:
              content: /* eslint-disable */
          - typescript
  graphback:
    model: ./model/**/*.graphql
    plugins:
      graphback-schema:
        format: graphql
        outputPath: ./src/schema/schema.graphql
